apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-test-deployment
  labels:
    app: simple-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-test
  template:
    metadata:
      labels:
        app: simple-test
    spec:
      containers:
        - name: simple-test-container
          image: simple-test-image
          ports:
            - containerPort: 3000